[package]
name = "ring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = {version="0.5.3", features=["all"]}
ctrlc = "3.4.0"
getopts = "0.2.13"
